### ISSUE TITLE
Error during conversion

### ISSUE THREAD

**Issue by jbeck22** [ntec-io/Email2Pdf#2]
getting a weird error when trying to convert an email that has a .png attachment

```
Converting Email: eml to html
Converting Email: html to pdf
Traceback (most recent call last):
File "email2pdf.py", line 53, in <module>
pdfkit.from_file(TMP_DIR + mail.subject + "/" + mail.subject + ".html",
File "/usr/local/lib/python3.8/dist-packages/pdfkit/api.py", line 49, in from_file
return r.to_pdf(output_path)
File "/usr/local/lib/python3.8/dist-packages/pdfkit/pdfkit.py", line 156, in to_pdf
raise IOError('wkhtmltopdf reported an error:\n' + stderr)

OSError: wkhtmltopdf reported an error:

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Loading page (1/2)
Error: Failed to load cid:image002.png@01D90642.492E9CA0, with network status code 301 and http status code 0 - Protocol "cid" is unknown

Error: Failed to load cid:image003.png@01D90642.492E9CA0, with network status code 301 and http status code 0 - Protocol "cid" is unknown

Exit with code 1 due to network error: ProtocolUnknownError

```

**Comment by ngoldack** [comment]
Hi, sorry for the late reply. 
It seems that pdfkit is having issues detecting the image.

It could also be a problem with the chilkatsoft lib that converts it to a html-file first. Unfortunately this lib is not Open Source, what makes it hard to trace the error.

I'm archiving this repo now, because I cannot give proper support under these circumstances.
